[tool.poetry]
name = "rd_soap"
version = "0.1.0"
description = ""
authors = ["Nutchanon Ninyawee <me@nutchanon.org>"]

[tool.poetry.dependencies]
python = "^3.8"
zeep = "^3.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
